/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// Location struct for Location
type Location struct {
	City string `json:"city,omitempty"`
	Province string `json:"province,omitempty"`
	Street string `json:"street,omitempty"`
}
