/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// UserInfo 用户参数
type UserInfo struct {
	// 机器人标识
	ApiKey string `json:"apiKey,omitempty"`
	// 用户唯一标识
	UserId string `json:"userId,omitempty"`
	// 群聊唯一标识
	GroupId string `json:"groupId,omitempty"`
	// 群内用户昵称
	UserIdName string `json:"userIdName,omitempty"`
}
