/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// InputText 文本信息
type InputText struct {
	Text string `json:"text,omitempty"`
}
