/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// Inspect struct for Inspect
type Inspect struct {
	Id string `json:"id,omitempty"`
	Question string `json:"question,omitempty"`
}
