/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// InputMedia struct for InputMedia
type InputMedia struct {
	// 音频地址
	Url string `json:"url,omitempty"`
}
