/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// PerceptionSelfInfo 地理位置信息
type PerceptionSelfInfo struct {
	Location map[string]interface{} `json:"location,omitempty"`
}
