/*
 * 图灵聊天机器人API
 *
 * 图灵聊天机器人API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package tuling
// ChatReq struct for ChatReq
type ChatReq struct {
	// 输入类型:0-文本(默认)、1-图片、2-音频
	ReqType int32 `json:"reqType,omitempty"`
	Perception Perception `json:"perception,omitempty"`
	UserInfo UserInfo `json:"userInfo,omitempty"`
}
